const xmlFile="/catalog/group3/section7/partslist.xml";
const xslPartsList="xml/parts_table.xsl"  


// generated by ChatGPT - with some prompting, but still impressive!

function generateTable(xml, xsl) {
    // Create an XSLT processor
    var xsltProcessor = new XSLTProcessor();
  
    // Import the stylesheet into the processor
    xsltProcessor.importStylesheet(xsl);
  
    // Transform the XML data using the stylesheet
    var fragment = xsltProcessor.transformToFragment(xml, document);
  
    // Insert the HTML into the page
    document.getElementById("table-partslist").replaceChildren();
    document.getElementById("table-partslist").appendChild(fragment);
}
  

function loadPartsList(menuItem) {
  const dir = menuItem.getAttribute("data-dir");
  const xmlPartsList = dir + menuItem.getAttribute("data-partslist");
  // Load the XML and XSL files, then generate the table
  loadXML(xmlPartsList, function(xml) {
    loadXML(xslPartsList, function(xsl) {
        generateTable(xml, xsl);
    });
  });
}  
  